### ISSUE TITLE
Create core app

### ISSUE THREAD

**Issue by davangcas** [davangcas/blaster_impresiones#6]
Se debe generar una nueva aplicacion dentro del proyecto con el nombre de ```core```

Agregar la app dentro de settings del proyecto
Generar un archivo dentro de la app llamado services
generar dentro de la app una carpeta llamada ```templates``` y dentro de esta carpeta, otra carpeta llamada ```core```
No se van a necesitar los archivos de url ni los de views por lo tanto se pueden eliminar
Tampoco se van a generar modelos en esta app

**Comment by lourain124** [comment]
Se realizó el issue con los requerimientos mencionados
